"""product circut_type filed change

Revision ID: 692cd5743687
Revises: 7ef973408fe5
Create Date: 2019-03-04 16:24:58.327903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '692cd5743687'
down_revision = '7ef973408fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'circuit_type',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_product_circuit_type'), 'product', ['circuit_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_circuit_type'), table_name='product')
    op.alter_column('product', 'circuit_type',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###
