"""add uploadimg

Revision ID: 6ca3a859af6c
Revises: f65bac140b39
Create Date: 2019-03-01 16:12:45.954999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca3a859af6c'
down_revision = 'f65bac140b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploadimg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(length=64), nullable=True),
    sa.Column('dir', sa.String(length=32), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploadimg_addtime'), 'uploadimg', ['addtime'], unique=False)
    op.create_index(op.f('ix_uploadimg_dir'), 'uploadimg', ['dir'], unique=False)
    op.create_index(op.f('ix_uploadimg_src'), 'uploadimg', ['src'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploadimg_src'), table_name='uploadimg')
    op.drop_index(op.f('ix_uploadimg_dir'), table_name='uploadimg')
    op.drop_index(op.f('ix_uploadimg_addtime'), table_name='uploadimg')
    op.drop_table('uploadimg')
    # ### end Alembic commands ###
