"""produvr

Revision ID: 7ef973408fe5
Revises: c7b7285fa68b
Create Date: 2019-03-04 15:40:55.279945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ef973408fe5'
down_revision = 'c7b7285fa68b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('bdwidth', sa.String(length=32), nullable=True),
    sa.Column('ip_num', sa.String(length=32), nullable=True),
    sa.Column('defends', sa.String(length=32), nullable=True),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.Column('circuit_type', sa.String(length=64), nullable=True),
    sa.Column('standard', sa.String(length=32), nullable=True),
    sa.Column('pro_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_defends'), 'product', ['defends'], unique=False)
    op.create_index(op.f('ix_product_ip_num'), 'product', ['ip_num'], unique=False)
    op.create_index(op.f('ix_product_price'), 'product', ['price'], unique=False)
    op.create_index(op.f('ix_product_pro_type'), 'product', ['pro_type'], unique=False)
    op.create_index(op.f('ix_product_standard'), 'product', ['standard'], unique=False)
    op.create_index(op.f('ix_product_title'), 'product', ['title'], unique=True)
    op.drop_index('ix_hotserver_disk', table_name='hotserver')
    op.drop_index('ix_hotserver_memory', table_name='hotserver')
    op.drop_index('ix_hotserver_price', table_name='hotserver')
    op.drop_index('ix_hotserver_title', table_name='hotserver')
    op.drop_table('hotserver')
    op.drop_index('ix_cabient_defends', table_name='cabient')
    op.drop_index('ix_cabient_ip_num', table_name='cabient')
    op.drop_index('ix_cabient_price', table_name='cabient')
    op.drop_index('ix_cabient_standard', table_name='cabient')
    op.drop_index('ix_cabient_title', table_name='cabient')
    op.drop_table('cabient')
    op.drop_index('ix_trustee_defends', table_name='trustee')
    op.drop_index('ix_trustee_ip_num', table_name='trustee')
    op.drop_index('ix_trustee_price', table_name='trustee')
    op.drop_index('ix_trustee_title', table_name='trustee')
    op.drop_table('trustee')
    op.drop_index('ix_higserver_bdwidth', table_name='higserver')
    op.drop_index('ix_higserver_disk', table_name='higserver')
    op.drop_index('ix_higserver_memory', table_name='higserver')
    op.drop_index('ix_higserver_price', table_name='higserver')
    op.drop_index('ix_higserver_title', table_name='higserver')
    op.drop_table('higserver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('higserver',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('cpu', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('memory', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('disk', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('bdwidth', mysql.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_higserver_title', 'higserver', ['title'], unique=True)
    op.create_index('ix_higserver_price', 'higserver', ['price'], unique=False)
    op.create_index('ix_higserver_memory', 'higserver', ['memory'], unique=False)
    op.create_index('ix_higserver_disk', 'higserver', ['disk'], unique=False)
    op.create_index('ix_higserver_bdwidth', 'higserver', ['bdwidth'], unique=False)
    op.create_table('trustee',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('bdwidth', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('ip_num', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('defends', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('circuit_type', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_trustee_title', 'trustee', ['title'], unique=True)
    op.create_index('ix_trustee_price', 'trustee', ['price'], unique=False)
    op.create_index('ix_trustee_ip_num', 'trustee', ['ip_num'], unique=False)
    op.create_index('ix_trustee_defends', 'trustee', ['defends'], unique=False)
    op.create_table('cabient',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('bdwidth', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('ip_num', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('defends', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('standard', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('circuit_type', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_cabient_title', 'cabient', ['title'], unique=True)
    op.create_index('ix_cabient_standard', 'cabient', ['standard'], unique=False)
    op.create_index('ix_cabient_price', 'cabient', ['price'], unique=False)
    op.create_index('ix_cabient_ip_num', 'cabient', ['ip_num'], unique=False)
    op.create_index('ix_cabient_defends', 'cabient', ['defends'], unique=False)
    op.create_table('hotserver',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('cpu', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('memory', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('disk', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_hotserver_title', 'hotserver', ['title'], unique=True)
    op.create_index('ix_hotserver_price', 'hotserver', ['price'], unique=False)
    op.create_index('ix_hotserver_memory', 'hotserver', ['memory'], unique=False)
    op.create_index('ix_hotserver_disk', 'hotserver', ['disk'], unique=False)
    op.drop_index(op.f('ix_product_title'), table_name='product')
    op.drop_index(op.f('ix_product_standard'), table_name='product')
    op.drop_index(op.f('ix_product_pro_type'), table_name='product')
    op.drop_index(op.f('ix_product_price'), table_name='product')
    op.drop_index(op.f('ix_product_ip_num'), table_name='product')
    op.drop_index(op.f('ix_product_defends'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
