"""article data

Revision ID: bfc5531daf62
Revises: 0fbdc69426a4
Create Date: 2019-03-02 16:50:30.395627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfc5531daf62'
down_revision = '0fbdc69426a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('info', sa.String(length=256), nullable=True),
    sa.Column('release_time', sa.String(length=128), nullable=True),
    sa.Column('click_count', sa.String(length=64), nullable=True),
    sa.Column('article_content', sa.Text(), nullable=True),
    sa.Column('article_type', sa.Integer(), nullable=True),
    sa.Column('cover_img', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_article_type'), 'article', ['article_type'], unique=False)
    op.create_index(op.f('ix_article_click_count'), 'article', ['click_count'], unique=False)
    op.create_index(op.f('ix_article_cover_img'), 'article', ['cover_img'], unique=False)
    op.create_index(op.f('ix_article_release_time'), 'article', ['release_time'], unique=False)
    op.create_index(op.f('ix_article_title'), 'article', ['title'], unique=True)
    op.drop_index('ix_news_click_count', table_name='news')
    op.drop_index('ix_news_cover_img', table_name='news')
    op.drop_index('ix_news_release_time', table_name='news')
    op.drop_index('ix_news_title', table_name='news')
    op.drop_table('news')
    op.drop_index('ix_notice_click_count', table_name='notice')
    op.drop_index('ix_notice_cover_img', table_name='notice')
    op.drop_index('ix_notice_release_time', table_name='notice')
    op.drop_index('ix_notice_title', table_name='notice')
    op.drop_table('notice')
    op.drop_index('ix_faq_click_count', table_name='faq')
    op.drop_index('ix_faq_cover_img', table_name='faq')
    op.drop_index('ix_faq_release_time', table_name='faq')
    op.drop_index('ix_faq_title', table_name='faq')
    op.drop_table('faq')
    op.drop_index('ix_dynamic_click_count', table_name='dynamic')
    op.drop_index('ix_dynamic_cover_img', table_name='dynamic')
    op.drop_index('ix_dynamic_release_time', table_name='dynamic')
    op.drop_index('ix_dynamic_title', table_name='dynamic')
    op.drop_table('dynamic')
    op.drop_index('ix_staff_click_count', table_name='staff')
    op.drop_index('ix_staff_cover_img', table_name='staff')
    op.drop_index('ix_staff_release_time', table_name='staff')
    op.drop_index('ix_staff_title', table_name='staff')
    op.drop_table('staff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('info', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('release_time', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('click_count', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('article_content', mysql.TEXT(), nullable=True),
    sa.Column('cover_img', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_staff_title', 'staff', ['title'], unique=True)
    op.create_index('ix_staff_release_time', 'staff', ['release_time'], unique=False)
    op.create_index('ix_staff_cover_img', 'staff', ['cover_img'], unique=False)
    op.create_index('ix_staff_click_count', 'staff', ['click_count'], unique=False)
    op.create_table('dynamic',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('info', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('release_time', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('click_count', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('cover_img', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('dynamic_content', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_dynamic_title', 'dynamic', ['title'], unique=True)
    op.create_index('ix_dynamic_release_time', 'dynamic', ['release_time'], unique=False)
    op.create_index('ix_dynamic_cover_img', 'dynamic', ['cover_img'], unique=False)
    op.create_index('ix_dynamic_click_count', 'dynamic', ['click_count'], unique=False)
    op.create_table('faq',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('info', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('release_time', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('click_count', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('cover_img', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('faq_content', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_faq_title', 'faq', ['title'], unique=True)
    op.create_index('ix_faq_release_time', 'faq', ['release_time'], unique=False)
    op.create_index('ix_faq_cover_img', 'faq', ['cover_img'], unique=False)
    op.create_index('ix_faq_click_count', 'faq', ['click_count'], unique=False)
    op.create_table('notice',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('info', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('release_time', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('click_count', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('cover_img', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('notice_content', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_notice_title', 'notice', ['title'], unique=True)
    op.create_index('ix_notice_release_time', 'notice', ['release_time'], unique=False)
    op.create_index('ix_notice_cover_img', 'notice', ['cover_img'], unique=False)
    op.create_index('ix_notice_click_count', 'notice', ['click_count'], unique=False)
    op.create_table('news',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('info', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('release_time', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('click_count', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('cover_img', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('new_content', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_news_title', 'news', ['title'], unique=True)
    op.create_index('ix_news_release_time', 'news', ['release_time'], unique=False)
    op.create_index('ix_news_cover_img', 'news', ['cover_img'], unique=False)
    op.create_index('ix_news_click_count', 'news', ['click_count'], unique=False)
    op.drop_index(op.f('ix_article_title'), table_name='article')
    op.drop_index(op.f('ix_article_release_time'), table_name='article')
    op.drop_index(op.f('ix_article_cover_img'), table_name='article')
    op.drop_index(op.f('ix_article_click_count'), table_name='article')
    op.drop_index(op.f('ix_article_article_type'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
