"""server add server_type field

Revision ID: c7b7285fa68b
Revises: bfc5531daf62
Create Date: 2019-03-04 14:05:22.842931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b7285fa68b'
down_revision = 'bfc5531daf62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('server_type', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_server_server_type'), 'server', ['server_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_server_type'), table_name='server')
    op.drop_column('server', 'server_type')
    # ### end Alembic commands ###
