"""first migrate

Revision ID: f65bac140b39
Revises: 
Create Date: 2019-02-28 16:20:30.356998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65bac140b39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('bdwidth', sa.String(length=32), nullable=True),
    sa.Column('ip_num', sa.String(length=32), nullable=True),
    sa.Column('defends', sa.String(length=32), nullable=True),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.Column('standard', sa.String(length=32), nullable=True),
    sa.Column('circuit_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cabient_defends'), 'cabient', ['defends'], unique=False)
    op.create_index(op.f('ix_cabient_ip_num'), 'cabient', ['ip_num'], unique=False)
    op.create_index(op.f('ix_cabient_price'), 'cabient', ['price'], unique=False)
    op.create_index(op.f('ix_cabient_standard'), 'cabient', ['standard'], unique=False)
    op.create_index(op.f('ix_cabient_title'), 'cabient', ['title'], unique=True)
    op.create_table('discount_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('info', sa.String(length=256), nullable=True),
    sa.Column('start_time', sa.String(length=128), nullable=True),
    sa.Column('end_time', sa.String(length=128), nullable=True),
    sa.Column('discount_content', sa.Text(), nullable=True),
    sa.Column('cover_img', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_active'), 'discount_img', ['active'], unique=False)
    op.create_index(op.f('ix_discount_cover_img'), 'discount_img', ['cover_img'], unique=False)
    op.create_index(op.f('ix_discount_end_time'), 'discount_img', ['end_time'], unique=False)
    op.create_index(op.f('ix_discount_start_time'), 'discount_img', ['start_time'], unique=False)
    op.create_index(op.f('ix_discount_title'), 'discount_img', ['title'], unique=True)
    op.create_table('dynamic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('info', sa.String(length=256), nullable=True),
    sa.Column('release_time', sa.String(length=128), nullable=True),
    sa.Column('click_count', sa.String(length=64), nullable=True),
    sa.Column('cover_img', sa.String(length=64), nullable=True),
    sa.Column('dynamic_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_click_count'), 'dynamic', ['click_count'], unique=False)
    op.create_index(op.f('ix_dynamic_cover_img'), 'dynamic', ['cover_img'], unique=False)
    op.create_index(op.f('ix_dynamic_release_time'), 'dynamic', ['release_time'], unique=False)
    op.create_index(op.f('ix_dynamic_title'), 'dynamic', ['title'], unique=True)
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('info', sa.String(length=256), nullable=True),
    sa.Column('release_time', sa.String(length=128), nullable=True),
    sa.Column('click_count', sa.String(length=64), nullable=True),
    sa.Column('cover_img', sa.String(length=64), nullable=True),
    sa.Column('faq_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_click_count'), 'faq', ['click_count'], unique=False)
    op.create_index(op.f('ix_faq_cover_img'), 'faq', ['cover_img'], unique=False)
    op.create_index(op.f('ix_faq_release_time'), 'faq', ['release_time'], unique=False)
    op.create_index(op.f('ix_faq_title'), 'faq', ['title'], unique=True)
    op.create_table('higserver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('cpu', sa.String(length=32), nullable=True),
    sa.Column('memory', sa.String(length=32), nullable=True),
    sa.Column('disk', sa.String(length=32), nullable=True),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.Column('bdwidth', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_higserver_bdwidth'), 'higserver', ['bdwidth'], unique=False)
    op.create_index(op.f('ix_higserver_disk'), 'higserver', ['disk'], unique=False)
    op.create_index(op.f('ix_higserver_memory'), 'higserver', ['memory'], unique=False)
    op.create_index(op.f('ix_higserver_price'), 'higserver', ['price'], unique=False)
    op.create_index(op.f('ix_higserver_title'), 'higserver', ['title'], unique=True)
    op.create_table('hotserver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('cpu', sa.String(length=32), nullable=True),
    sa.Column('memory', sa.String(length=32), nullable=True),
    sa.Column('disk', sa.String(length=32), nullable=True),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotserver_disk'), 'hotserver', ['disk'], unique=False)
    op.create_index(op.f('ix_hotserver_memory'), 'hotserver', ['memory'], unique=False)
    op.create_index(op.f('ix_hotserver_price'), 'hotserver', ['price'], unique=False)
    op.create_index(op.f('ix_hotserver_title'), 'hotserver', ['title'], unique=True)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('info', sa.String(length=256), nullable=True),
    sa.Column('release_time', sa.String(length=128), nullable=True),
    sa.Column('click_count', sa.String(length=64), nullable=True),
    sa.Column('cover_img', sa.String(length=64), nullable=True),
    sa.Column('new_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_click_count'), 'news', ['click_count'], unique=False)
    op.create_index(op.f('ix_news_cover_img'), 'news', ['cover_img'], unique=False)
    op.create_index(op.f('ix_news_release_time'), 'news', ['release_time'], unique=False)
    op.create_index(op.f('ix_news_title'), 'news', ['title'], unique=True)
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('info', sa.String(length=256), nullable=True),
    sa.Column('release_time', sa.String(length=128), nullable=True),
    sa.Column('click_count', sa.String(length=64), nullable=True),
    sa.Column('cover_img', sa.String(length=64), nullable=True),
    sa.Column('notice_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_click_count'), 'notice', ['click_count'], unique=False)
    op.create_index(op.f('ix_notice_cover_img'), 'notice', ['cover_img'], unique=False)
    op.create_index(op.f('ix_notice_release_time'), 'notice', ['release_time'], unique=False)
    op.create_index(op.f('ix_notice_title'), 'notice', ['title'], unique=True)
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('cpu', sa.String(length=32), nullable=True),
    sa.Column('memory', sa.String(length=32), nullable=True),
    sa.Column('disk', sa.String(length=32), nullable=True),
    sa.Column('bdwidth', sa.String(length=32), nullable=True),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.Column('server_region', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_bdwidth'), 'server', ['bdwidth'], unique=False)
    op.create_index(op.f('ix_server_disk'), 'server', ['disk'], unique=False)
    op.create_index(op.f('ix_server_memory'), 'server', ['memory'], unique=False)
    op.create_index(op.f('ix_server_price'), 'server', ['price'], unique=False)
    op.create_index(op.f('ix_server_title'), 'server', ['title'], unique=True)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('info', sa.String(length=256), nullable=True),
    sa.Column('release_time', sa.String(length=128), nullable=True),
    sa.Column('click_count', sa.String(length=64), nullable=True),
    sa.Column('article_content', sa.Text(), nullable=True),
    sa.Column('cover_img', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_click_count'), 'staff', ['click_count'], unique=False)
    op.create_index(op.f('ix_staff_cover_img'), 'staff', ['cover_img'], unique=False)
    op.create_index(op.f('ix_staff_release_time'), 'staff', ['release_time'], unique=False)
    op.create_index(op.f('ix_staff_title'), 'staff', ['title'], unique=True)
    op.create_table('trustee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('bdwidth', sa.String(length=32), nullable=True),
    sa.Column('ip_num', sa.String(length=32), nullable=True),
    sa.Column('defends', sa.String(length=32), nullable=True),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.Column('circuit_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trustee_defends'), 'trustee', ['defends'], unique=False)
    op.create_index(op.f('ix_trustee_ip_num'), 'trustee', ['ip_num'], unique=False)
    op.create_index(op.f('ix_trustee_price'), 'trustee', ['price'], unique=False)
    op.create_index(op.f('ix_trustee_title'), 'trustee', ['title'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_ip'), 'user', ['ip'], unique=False)
    op.create_index(op.f('ix_user_login_time'), 'user', ['login_time'], unique=False)
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_login_time'), table_name='user')
    op.drop_index(op.f('ix_user_ip'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_trustee_title'), table_name='trustee')
    op.drop_index(op.f('ix_trustee_price'), table_name='trustee')
    op.drop_index(op.f('ix_trustee_ip_num'), table_name='trustee')
    op.drop_index(op.f('ix_trustee_defends'), table_name='trustee')
    op.drop_table('trustee')
    op.drop_index(op.f('ix_staff_title'), table_name='staff')
    op.drop_index(op.f('ix_staff_release_time'), table_name='staff')
    op.drop_index(op.f('ix_staff_cover_img'), table_name='staff')
    op.drop_index(op.f('ix_staff_click_count'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_server_title'), table_name='server')
    op.drop_index(op.f('ix_server_price'), table_name='server')
    op.drop_index(op.f('ix_server_memory'), table_name='server')
    op.drop_index(op.f('ix_server_disk'), table_name='server')
    op.drop_index(op.f('ix_server_bdwidth'), table_name='server')
    op.drop_table('server')
    op.drop_index(op.f('ix_notice_title'), table_name='notice')
    op.drop_index(op.f('ix_notice_release_time'), table_name='notice')
    op.drop_index(op.f('ix_notice_cover_img'), table_name='notice')
    op.drop_index(op.f('ix_notice_click_count'), table_name='notice')
    op.drop_table('notice')
    op.drop_index(op.f('ix_news_title'), table_name='news')
    op.drop_index(op.f('ix_news_release_time'), table_name='news')
    op.drop_index(op.f('ix_news_cover_img'), table_name='news')
    op.drop_index(op.f('ix_news_click_count'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_hotserver_title'), table_name='hotserver')
    op.drop_index(op.f('ix_hotserver_price'), table_name='hotserver')
    op.drop_index(op.f('ix_hotserver_memory'), table_name='hotserver')
    op.drop_index(op.f('ix_hotserver_disk'), table_name='hotserver')
    op.drop_table('hotserver')
    op.drop_index(op.f('ix_higserver_title'), table_name='higserver')
    op.drop_index(op.f('ix_higserver_price'), table_name='higserver')
    op.drop_index(op.f('ix_higserver_memory'), table_name='higserver')
    op.drop_index(op.f('ix_higserver_disk'), table_name='higserver')
    op.drop_index(op.f('ix_higserver_bdwidth'), table_name='higserver')
    op.drop_table('higserver')
    op.drop_index(op.f('ix_faq_title'), table_name='faq')
    op.drop_index(op.f('ix_faq_release_time'), table_name='faq')
    op.drop_index(op.f('ix_faq_cover_img'), table_name='faq')
    op.drop_index(op.f('ix_faq_click_count'), table_name='faq')
    op.drop_table('faq')
    op.drop_index(op.f('ix_dynamic_title'), table_name='dynamic')
    op.drop_index(op.f('ix_dynamic_release_time'), table_name='dynamic')
    op.drop_index(op.f('ix_dynamic_cover_img'), table_name='dynamic')
    op.drop_index(op.f('ix_dynamic_click_count'), table_name='dynamic')
    op.drop_table('dynamic')
    op.drop_index(op.f('ix_discount_title'), table_name='discount_img')
    op.drop_index(op.f('ix_discount_start_time'), table_name='discount_img')
    op.drop_index(op.f('ix_discount_end_time'), table_name='discount_img')
    op.drop_index(op.f('ix_discount_cover_img'), table_name='discount_img')
    op.drop_index(op.f('ix_discount_active'), table_name='discount_img')
    op.drop_table('discount_img')
    op.drop_index(op.f('ix_cabient_title'), table_name='cabient')
    op.drop_index(op.f('ix_cabient_standard'), table_name='cabient')
    op.drop_index(op.f('ix_cabient_price'), table_name='cabient')
    op.drop_index(op.f('ix_cabient_ip_num'), table_name='cabient')
    op.drop_index(op.f('ix_cabient_defends'), table_name='cabient')
    op.drop_table('cabient')
    # ### end Alembic commands ###
